In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('master.csv')
df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [3]:
df.dtypes

country                object
year                    int64
sex                    object
age                    object
suicides_no             int64
population              int64
suicides/100k pop     float64
country-year           object
HDI for year          float64
 gdp_for_year ($)      object
gdp_per_capita ($)      int64
generation             object
dtype: object

df = pd.read_csv('master.csv', header=0,  decimal='.', thousands=',')

In [4]:
df.dtypes

country                object
year                    int64
sex                    object
age                    object
suicides_no             int64
population              int64
suicides/100k pop     float64
country-year           object
HDI for year          float64
 gdp_for_year ($)      object
gdp_per_capita ($)      int64
generation             object
dtype: object

In [5]:
df.tail()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [6]:
df['gdp_per_capita ($)']

0         796
1         796
2         796
3         796
4         796
5         796
6         796
7         796
8         796
9         796
10        796
11        796
12        769
13        769
14        769
15        769
16        769
17        769
18        769
19        769
20        769
21        769
22        769
23        769
24        833
25        833
26        833
27        833
28        833
29        833
         ...
27790    1964
27791    1964
27792    1964
27793    1964
27794    1964
27795    1964
27796    2150
27797    2150
27798    2150
27799    2150
27800    2150
27801    2150
27802    2150
27803    2150
27804    2150
27805    2150
27806    2150
27807    2150
27808    2309
27809    2309
27810    2309
27811    2309
27812    2309
27813    2309
27814    2309
27815    2309
27816    2309
27817    2309
27818    2309
27819    2309
Name: gdp_per_capita ($), Length: 27820, dtype: int64

In [7]:
df['gdp_for_year ($)'].dtype

KeyError: 'gdp_for_year ($)'

In [ ]:
df['gdp_for_year ($)']

In [ ]:
df['HDI for year']

In [ ]:
df.info

In [ ]:
df.describe()

In [ ]:
df.loc[:,'year']

In [ ]:
df.loc[0,:]

In [ ]:
df.loc[:,'year']

In [ ]:
df[df['generation']=='Boomers']

In [ ]:
df[df['country']].unique

In [8]:
df.unique(df['country'])

AttributeError: 'DataFrame' object has no attribute 'unique'

In [9]:
df.(df['country']).unique()

SyntaxError: invalid syntax (<ipython-input-9-13f7f825f102>, line 1)

In [10]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [11]:
df.groupby('country')

In [12]:
grouper = df.groupby('country')

In [13]:
grouper

In [20]:
grouper.groups

{'Albania': Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
             ...
             254, 255, 256, 257, 258, 259, 260, 261, 262, 263],
            dtype='int64', length=264),
 'Antigua and Barbuda': Int64Index([264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
             ...
             578, 579, 580, 581, 582, 583, 584, 585, 586, 587],
            dtype='int64', length=324),
 'Argentina': Int64Index([588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
             ...
             950, 951, 952, 953, 954, 955, 956, 957, 958, 959],
            dtype='int64', length=372),
 'Armenia': Int64Index([ 960,  961,  962,  963,  964,  965,  966,  967,  968,  969,
             ...
             1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257],
            dtype='int64', length=298),
 'Aruba': Int64Index([1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267,
             ...
             1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425],
            dtype='int64', length=168),
 'Australia': Int64Index([1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435,
             ...
             1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785],
            dtype='int64', length=360),
 'Austria': Int64Index([1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795,
             ...
             2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167],
            dtype='int64', length=382),
 'Azerbaijan': Int64Index([2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177,
             ...
             2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359],
            dtype='int64', length=192),
 'Bahamas': Int64Index([2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369,
             ...
             2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635],
            dtype='int64', length=276),
 'Bahrain': Int64Index([2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645,
             ...
             2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887],
            dtype='int64', length=252),
 'Barbados': Int64Index([2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897,
             ...
             3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187],
            dtype='int64', length=300),
 'Belarus': Int64Index([3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197,
             ...
             3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439],
            dtype='int64', length=252),
 'Belgium': Int64Index([3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449,
             ...
             3802, 3803, 3804, 3805, 3806, 3807, 3808, 3809, 3810, 3811],
            dtype='int64', length=372),
 'Belize': Int64Index([3812, 3813, 3814, 3815, 3816, 3817, 3818, 3819, 3820, 3821,
             ...
             4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147],
            dtype='int64', length=336),
 'Bosnia and Herzegovina': Int64Index([4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158,
             4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4169,
             4170, 4171],
            dtype='int64'),
 'Brazil': Int64Index([4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181,
             ...
             4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541, 4542, 4543],
            dtype='int64', length=372),
 'Bulgaria': Int64Index([4544, 4545, 4546, 4547, 4548, 4549, 4550, 4551, 4552, 4553,
             ...
             4894, 4895, 4896, 4897, 4898, 4899, 4900, 4901, 4902, 4903],
            dtype='int64', length=360),
 'Cabo Verde': Int64Index([4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914,
             4915],
            dtype='int64'),
 'Canada': Int64Index([4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925,
             ...
             5254, 5255, 5256, 5257, 5258, 5259, 5260, 5261, 5262, 5263],
            dtype='int64', length=348),
 'Chile': Int64Index([5264, 5265, 5266, 5267, 5268, 5269, 5270, 5271, 5272, 5273,
             ...
             5626, 5627, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635],
            dtype='int64', length=372),
 'Colombia': Int64Index([5636, 5637, 5638, 5639, 5640, 5641, 5642, 5643, 5644, 5645,
             ...
             5998, 5999, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007],
            dtype='int64', length=372),
 'Costa Rica': Int64Index([6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017,
             ...
             6358, 6359, 6360, 6361, 6362, 6363, 6364, 6365, 6366, 6367],
            dtype='int64', length=360),
 'Croatia': Int64Index([6368, 6369, 6370, 6371, 6372, 6373, 6374, 6375, 6376, 6377,
             ...
             6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6628, 6629],
            dtype='int64', length=262),
 'Cuba': Int64Index([6630, 6631, 6632, 6633, 6634, 6635, 6636, 6637, 6638, 6639,
             ...
             6908, 6909, 6910, 6911, 6912, 6913, 6914, 6915, 6916, 6917],
            dtype='int64', length=288),
 'Cyprus': Int64Index([6918, 6919, 6920, 6921, 6922, 6923, 6924, 6925, 6926, 6927,
             ...
             7086, 7087, 7088, 7089, 7090, 7091, 7092, 7093, 7094, 7095],
            dtype='int64', length=178),
 'Czech Republic': Int64Index([7096, 7097, 7098, 7099, 7100, 7101, 7102, 7103, 7104, 7105,
             ...
             7408, 7409, 7410, 7411, 7412, 7413, 7414, 7415, 7416, 7417],
            dtype='int64', length=322),
 'Denmark': Int64Index([7418, 7419, 7420, 7421, 7422, 7423, 7424, 7425, 7426, 7427,
             ...
             7672, 7673, 7674, 7675, 7676, 7677, 7678, 7679, 7680, 7681],
            dtype='int64', length=264),
 'Dominica': Int64Index([7682, 7683, 7684, 7685, 7686, 7687, 7688, 7689, 7690, 7691, 7692,
             7693],
            dtype='int64'),
 'Ecuador': Int64Index([7694, 7695, 7696, 7697, 7698, 7699, 7700, 7701, 7702, 7703,
             ...
             8056, 8057, 8058, 8059, 8060, 8061, 8062, 8063, 8064, 8065],
            dtype='int64', length=372),
 'El Salvador': Int64Index([8066, 8067, 8068, 8069, 8070, 8071, 8072, 8073, 8074, 8075,
             ...
             8344, 8345, 8346, 8347, 8348, 8349, 8350, 8351, 8352, 8353],
            dtype='int64', length=288),
 'Estonia': Int64Index([8354, 8355, 8356, 8357, 8358, 8359, 8360, 8361, 8362, 8363,
             ...
             8596, 8597, 8598, 8599, 8600, 8601, 8602, 8603, 8604, 8605],
            dtype='int64', length=252),
 'Fiji': Int64Index([8606, 8607, 8608, 8609, 8610, 8611, 8612, 8613, 8614, 8615,
             ...
             8728, 8729, 8730, 8731, 8732, 8733, 8734, 8735, 8736, 8737],
            dtype='int64', length=132),
 'Finland': Int64Index([8738, 8739, 8740, 8741, 8742, 8743, 8744, 8745, 8746, 8747,
             ...
             9076, 9077, 9078, 9079, 9080, 9081, 9082, 9083, 9084, 9085],
            dtype='int64', length=348),
 'France': Int64Index([9086, 9087, 9088, 9089, 9090, 9091, 9092, 9093, 9094, 9095,
             ...
             9436, 9437, 9438, 9439, 9440, 9441, 9442, 9443, 9444, 9445],
            dtype='int64', length=360),
 'Georgia': Int64Index([9446, 9447, 9448, 9449, 9450, 9451, 9452, 9453, 9454, 9455,
             ...
             9700, 9701, 9702, 9703, 9704, 9705, 9706, 9707, 9708, 9709],
            dtype='int64', length=264),
 'Germany': Int64Index([ 9710,  9711,  9712,  9713,  9714,  9715,  9716,  9717,  9718,
              9719,
             ...
             10012, 10013, 10014, 10015, 10016, 10017, 10018, 10019, 10020,
             10021],
            dtype='int64', length=312),
 'Greece': Int64Index([10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029, 10030,
             10031,
             ...
             10384, 10385, 10386, 10387, 10388, 10389, 10390, 10391, 10392,
             10393],
            dtype='int64', length=372),
 'Grenada': Int64Index([10394, 10395, 10396, 10397, 10398, 10399, 10400, 10401, 10402,
             10403,
             ...
             10694, 10695, 10696, 10697, 10698, 10699, 10700, 10701, 10702,
             10703],
            dtype='int64', length=310),
 'Guatemala': Int64Index([10704, 10705, 10706, 10707, 10708, 10709, 10710, 10711, 10712,
             10713,
             ...
             11054, 11055, 11056, 11057, 11058, 11059, 11060, 11061, 11062,
             11063],
            dtype='int64', length=360),
 'Guyana': Int64Index([11064, 11065, 11066, 11067, 11068, 11069, 11070, 11071, 11072,
             11073,
             ...
             11354, 11355, 11356, 11357, 11358, 11359, 11360, 11361, 11362,
             11363],
            dtype='int64', length=300),
 'Hungary': Int64Index([11364, 11365, 11366, 11367, 11368, 11369, 11370, 11371, 11372,
             11373,
             ...
             11664, 11665, 11666, 11667, 11668, 11669, 11670, 11671, 11672,
             11673],
            dtype='int64', length=310),
 'Iceland': Int64Index([11674, 11675, 11676, 11677, 11678, 11679, 11680, 11681, 11682,
             11683,
             ...
             12046, 12047, 12048, 12049, 12050, 12051, 12052, 12053, 12054,
             12055],
            dtype='int64', length=382),
 'Ireland': Int64Index([12056, 12057, 12058, 12059, 12060, 12061, 12062, 12063, 12064,
             12065,
             ...
             12406, 12407, 12408, 12409, 12410, 12411, 12412, 12413, 12414,
             12415],
            dtype='int64', length=360),
 'Israel': Int64Index([12416, 12417, 12418, 12419, 12420, 12421, 12422, 12423, 12424,
             12425,
             ...
             12778, 12779, 12780, 12781, 12782, 12783, 12784, 12785, 12786,
             12787],
            dtype='int64', length=372),
 'Italy': Int64Index([12788, 12789, 12790, 12791, 12792, 12793, 12794, 12795, 12796,
             12797,
             ...
             13150, 13151, 13152, 13153, 13154, 13155, 13156, 13157, 13158,
             13159],
            dtype='int64', length=372),
 'Jamaica': Int64Index([13160, 13161, 13162, 13163, 13164, 13165, 13166, 13167, 13168,
             13169,
             ...
             13354, 13355, 13356, 13357, 13358, 13359, 13360, 13361, 13362,
             13363],
            dtype='int64', length=204),
 'Japan': Int64Index([13364, 13365, 13366, 13367, 13368, 13369, 13370, 13371, 13372,
             13373,
             ...
             13726, 13727, 13728, 13729, 13730, 13731, 13732, 13733, 13734,
             13735],
            dtype='int64', length=372),
 'Kazakhstan': Int64Index([13736, 13737, 13738, 13739, 13740, 13741, 13742, 13743, 13744,
             13745,
             ...
             14038, 14039, 14040, 14041, 14042, 14043, 14044, 14045, 14046,
             14047],
            dtype='int64', length=312),
 'Kiribati': Int64Index([14048, 14049, 14050, 14051, 14052, 14053, 14054, 14055, 14056,
             14057,
             ...
             14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177, 14178,
             14179],
            dtype='int64', length=132),
 'Kuwait': Int64Index([14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187, 14188,
             14189,
             ...
             14470, 14471, 14472, 14473, 14474, 14475, 14476, 14477, 14478,
             14479],
            dtype='int64', length=300),
 'Kyrgyzstan': Int64Index([14480, 14481, 14482, 14483, 14484, 14485, 14486, 14487, 14488,
             14489,
             ...
             14782, 14783, 14784, 14785, 14786, 14787, 14788, 14789, 14790,
             14791],
            dtype='int64', length=312),
 'Latvia': Int64Index([14792, 14793, 14794, 14795, 14796, 14797, 14798, 14799, 14800,
             14801,
             ...
             15034, 15035, 15036, 15037, 15038, 15039, 15040, 15041, 15042,
             15043],
            dtype='int64', length=252),
 'Lithuania': Int64Index([15044, 15045, 15046, 15047, 15048, 15049, 15050, 15051, 15052,
             15053,
             ...
             15296, 15297, 15298, 15299, 15300, 15301, 15302, 15303, 15304,
             15305],
            dtype='int64', length=262),
 'Luxembourg': Int64Index([15306, 15307, 15308, 15309, 15310, 15311, 15312, 15313, 15314,
             15315,
             ...
             15668, 15669, 15670, 15671, 15672, 15673, 15674, 15675, 15676,
             15677],
            dtype='int64', length=372),
 'Macau': Int64Index([15678, 15679, 15680, 15681, 15682, 15683, 15684, 15685, 15686,
             15687, 15688, 15689],
            dtype='int64'),
 'Maldives': Int64Index([15690, 15691, 15692, 15693, 15694, 15695, 15696, 15697, 15698,
             15699,
             ...
             15800, 15801, 15802, 15803, 15804, 15805, 15806, 15807, 15808,
             15809],
            dtype='int64', length=120),
 'Malta': Int64Index([15810, 15811, 15812, 15813, 15814, 15815, 15816, 15817, 15818,
             15819,
             ...
             16172, 16173, 16174, 16175, 16176, 16177, 16178, 16179, 16180,
             16181],
            dtype='int64', length=372),
 'Mauritius': Int64Index([16182, 16183, 16184, 16185, 16186, 16187, 16188, 16189, 16190,
             16191,
             ...
             16554, 16555, 16556, 16557, 16558, 16559, 16560, 16561, 16562,
             16563],
            dtype='int64', length=382),
 'Mexico': Int64Index([16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
             16573,
             ...
             16926, 16927, 16928, 16929, 16930, 16931, 16932, 16933, 16934,
             16935],
            dtype='int64', length=372),
 'Mongolia': Int64Index([16936, 16937, 16938, 16939, 16940, 16941, 16942, 16943, 16944,
             16945],
            dtype='int64'),
 'Montenegro': Int64Index([16946, 16947, 16948, 16949, 16950, 16951, 16952, 16953, 16954,
             16955,
             ...
             17056, 17057, 17058, 17059, 17060, 17061, 17062, 17063, 17064,
             17065],
            dtype='int64', length=120),
 'Netherlands': Int64Index([17066, 17067, 17068, 17069, 17070, 17071, 17072, 17073, 17074,
             17075,
             ...
             17438, 17439, 17440, 17441, 17442, 17443, 17444, 17445, 17446,
             17447],
            dtype='int64', length=382),
 'New Zealand': Int64Index([17448, 17449, 17450, 17451, 17452, 17453, 17454, 17455, 17456,
             17457,
             ...
             17786, 17787, 17788, 17789, 17790, 17791, 17792, 17793, 17794,
             17795],
            dtype='int64', length=348),
 'Nicaragua': Int64Index([17796, 17797, 17798, 17799, 17800, 17801, 17802, 17803, 17804,
             17805, 17806, 17807, 17808, 17809, 17810, 17811, 17812, 17813,
             17814, 17815, 17816, 17817, 17818, 17819, 17820, 17821, 17822,
             17823, 17824, 17825, 17826, 17827, 17828, 17829, 17830, 17831,
             17832, 17833, 17834, 17835, 17836, 17837, 17838, 17839, 17840,
             17841, 17842, 17843, 17844, 17845, 17846, 17847, 17848, 17849,
             17850, 17851, 17852, 17853, 17854, 17855, 17856, 17857, 17858,
             17859, 17860, 17861, 17862, 17863, 17864, 17865, 17866, 17867],
            dtype='int64'),
 'Norway': Int64Index([17868, 17869, 17870, 17871, 17872, 17873, 17874, 17875, 17876,
             17877,
             ...
             18218, 18219, 18220, 18221, 18222, 18223, 18224, 18225, 18226,
             18227],
            dtype='int64', length=360),
 'Oman': Int64Index([18228, 18229, 18230, 18231, 18232, 18233, 18234, 18235, 18236,
             18237, 18238, 18239, 18240, 18241, 18242, 18243, 18244, 18245,
             18246, 18247, 18248, 18249, 18250, 18251, 18252, 18253, 18254,
             18255, 18256, 18257, 18258, 18259, 18260, 18261, 18262, 18263],
            dtype='int64'),
 'Panama': Int64Index([18264, 18265, 18266, 18267, 18268, 18269, 18270, 18271, 18272,
             18273,
             ...
             18554, 18555, 18556, 18557, 18558, 18559, 18560, 18561, 18562,
             18563],
            dtype='int64', length=300),
 'Paraguay': Int64Index([18564, 18565, 18566, 18567, 18568, 18569, 18570, 18571, 18572,
             18573,
             ...
             18878, 18879, 18880, 18881, 18882, 18883, 18884, 18885, 18886,
             18887],
            dtype='int64', length=324),
 'Philippines': Int64Index([18888, 18889, 18890, 18891, 18892, 18893, 18894, 18895, 18896,
             18897,
             ...
             19058, 19059, 19060, 19061, 19062, 19063, 19064, 19065, 19066,
             19067],
            dtype='int64', length=180),
 'Poland': Int64Index([19068, 19069, 19070, 19071, 19072, 19073, 19074, 19075, 19076,
             19077,
             ...
             19346, 19347, 19348, 19349, 19350, 19351, 19352, 19353, 19354,
             19355],
            dtype='int64', length=288),
 'Portugal': Int64Index([19356, 19357, 19358, 19359, 19360, 19361, 19362, 19363, 19364,
             19365,
             ...
             19670, 19671, 19672, 19673, 19674, 19675, 19676, 19677, 19678,
             19679],
            dtype='int64', length=324),
 'Puerto Rico': Int64Index([19680, 19681, 19682, 19683, 19684, 19685, 19686, 19687, 19688,
             19689,
             ...
             20042, 20043, 20044, 20045, 20046, 20047, 20048, 20049, 20050,
             20051],
            dtype='int64', length=372),
 'Qatar': Int64Index([20052, 20053, 20054, 20055, 20056, 20057, 20058, 20059, 20060,
             20061,
             ...
             20220, 20221, 20222, 20223, 20224, 20225, 20226, 20227, 20228,
             20229],
            dtype='int64', length=178),
 'Republic of Korea': Int64Index([20230, 20231, 20232, 20233, 20234, 20235, 20236, 20237, 20238,
             20239,
             ...
             20592, 20593, 20594, 20595, 20596, 20597, 20598, 20599, 20600,
             20601],
            dtype='int64', length=372),
 'Romania': Int64Index([20602, 20603, 20604, 20605, 20606, 20607, 20608, 20609, 20610,
             20611,
             ...
             20926, 20927, 20928, 20929, 20930, 20931, 20932, 20933, 20934,
             20935],
            dtype='int64', length=334),
 'Russian Federation': Int64Index([20936, 20937, 20938, 20939, 20940, 20941, 20942, 20943, 20944,
             20945,
             ...
             21250, 21251, 21252, 21253, 21254, 21255, 21256, 21257, 21258,
             21259],
            dtype='int64', length=324),
 'Saint Kitts and Nevis': Int64Index([21260, 21261, 21262, 21263, 21264, 21265, 21266, 21267, 21268,
             21269, 21270, 21271, 21272, 21273, 21274, 21275, 21276, 21277,
             21278, 21279, 21280, 21281, 21282, 21283, 21284, 21285, 21286,
             21287, 21288, 21289, 21290, 21291, 21292, 21293, 21294, 21295],
            dtype='int64'),
 'Saint Lucia': Int64Index([21296, 21297, 21298, 21299, 21300, 21301, 21302, 21303, 21304,
             21305,
             ...
             21622, 21623, 21624, 21625, 21626, 21627, 21628, 21629, 21630,
             21631],
            dtype='int64', length=336),
 'Saint Vincent and Grenadines': Int64Index([21632, 21633, 21634, 21635, 21636, 21637, 21638, 21639, 21640,
             21641,
             ...
             21922, 21923, 21924, 21925, 21926, 21927, 21928, 21929, 21930,
             21931],
            dtype='int64', length=300),
 'San Marino': Int64Index([21932, 21933, 21934, 21935, 21936, 21937, 21938, 21939, 21940,
             21941, 21942, 21943, 21944, 21945, 21946, 21947, 21948, 21949,
             21950, 21951, 21952, 21953, 21954, 21955, 21956, 21957, 21958,
             21959, 21960, 21961, 21962, 21963, 21964, 21965, 21966, 21967],
            dtype='int64'),
 'Serbia': Int64Index([21968, 21969, 21970, 21971, 21972, 21973, 21974, 21975, 21976,
             21977,
             ...
             22174, 22175, 22176, 22177, 22178, 22179, 22180, 22181, 22182,
             22183],
            dtype='int64', length=216),
 'Seychelles': Int64Index([22184, 22185, 22186, 22187, 22188, 22189, 22190, 22191, 22192,
             22193,
             ...

In [15]:
grouper.groupby(1)

AttributeError: Cannot access callable attribute 'groupby' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [16]:
grouper.get_group(1)

KeyError: 1

In [19]:
grouper.get_group(1)

KeyError: 1